spring.application.name=pakubakupaku_ECsite
#この下の文を入れると起動した
# 既存の設定を上書きしてください
spring.datasource.url=jdbc:postgresql://localhost:5432/pakubakupaku_ecsite
#上の文を変更するかを要相談いったんはこの形で進める
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# 起動時の自動スクリプトを一時停止
#spring.sql.init.mode=never


#spring.datasource.url=jdbc:postgresql://localhost:5432/Pakubakupaku_ECsite
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.datasource.driver-class-name=org.postgresql.Driver

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

#なぜかalwaysにしたらエラーが発生してしまう
spring.sql.init.mode=always


#エラーレポート（山本）alwaysにしてエラーが発生した原因は
#spring.datasource.url=jdbc:postgresql://localhost:5432/Pakubakupaku_ECsite
#のPakubakupaku_ECsiteというデータベースをゾウさんで作ってなかったから
#Ai曰くデータベースはすべて小文字が良いらしいのでどうするかをにのに聞く