spring.application.name=pakubakupaku_ECsite

spring.datasource.url=jdbc:postgresql://localhost:5432/Pakubakupaku_ECsite
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

spring.sql.init.mode=always