DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS game_play_history CASCADE;
DROP TABLE IF EXISTS ai_growth CASCADE;
DROP TABLE IF EXISTS point_history CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS regions CASCADE;
DROP TABLE IF EXISTS ranks CASCADE;

CREATE TABLE ranks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rank_name VARCHAR(100) NOT NULL,
    min_amount INTEGER NOT NULL,
    point_rate DECIMAL(5,2) NOT NULL
);

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    address VARCHAR(255),
    phone VARCHAR(20),
    point INTEGER NOT NULL DEFAULT 0,
    total_purchase_amount INTEGER NOT NULL DEFAULT 0,
    rank_id INTEGER NOT NULL,

    CONSTRAINT fk_users_rank
        FOREIGN KEY (rank_id)
        REFERENCES ranks(id)
);

CREATE TABLE categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(100) NOT NULL
);

CREATE TABLE regions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_name VARCHAR(100) NOT NULL
);

CREATE TABLE products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(150) NOT NULL,
    description TEXT,
    price INTEGER NOT NULL,
    stock INTEGER NOT NULL DEFAULT 0,
    image_url VARCHAR(255),
    category_id INTEGER NOT NULL,
    region_id INTEGER NOT NULL,

    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id)
        REFERENCES categories(id),

    CONSTRAINT fk_products_region
        FOREIGN KEY (region_id)
        REFERENCES regions(id)
);

CREATE TABLE orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    shipping_address VARCHAR(255) NOT NULL,
    order_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total_amount INTEGER NOT NULL,
    used_point INTEGER NOT NULL DEFAULT 0,
    earned_point INTEGER NOT NULL DEFAULT 0,
    order_status VARCHAR(50) NOT NULL DEFAULT 'ORDERED',

    CONSTRAINT fk_orders_user
        FOREIGN KEY (user_id)
        REFERENCES users(id),

    CONSTRAINT ck_orders_status
        CHECK (order_status IN ('ORDERED', 'SHIPPED', 'CANCELED'))
);

CREATE TABLE order_items (
    order_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    product_price INTEGER NOT NULL,

    PRIMARY KEY (order_id, product_id),

    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id)
        REFERENCES orders(id),

    CONSTRAINT fk_order_items_product
        FOREIGN KEY (product_id)
        REFERENCES products(id)
);

CREATE TABLE point_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    point_change INTEGER NOT NULL,
    reason VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_point_history_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
);

CREATE TABLE ai_growth (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    growth_stage INTEGER NOT NULL DEFAULT 1,
    personality VARCHAR(50) NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    chara_image_url VARCHAR(255) NOT NULL,

    CONSTRAINT fk_ai_growth_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
);

CREATE TABLE game_play_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    bet_point INTEGER NOT NULL,
    result BOOLEAN NOT NULL,
    earned_point INTEGER NOT NULL DEFAULT 0,
    played_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_game_play_history_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
);